# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FgMobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for FgMobile
  # pod 'AppAuth', '>= 0.94'
  # pod 'RNGestureHandler', :podspec => '../node_modules/react-native-gesture-handler/RNGestureHandler.podspec'


  

  target 'FgMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'FgMobile-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FgMobile-tvOS

  target 'FgMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
